#pragma once

#include <cstdint>
#include <memory>
#include <stdexcept>
#include <type_traits>
#include <utility>
#include <vector>

#include <vamp/bindings/python/array_helpers.hh>
#include <vamp/bindings/python/space_helper.hh>

#include <vamp/collision/environment.hh>
#include <vamp/planning/constraints/parameterized_local_planner.hh>
#include <vamp/planning/planner.hh>
#include <vamp/planning/planners/aorrtc.hh>
#include <vamp/planning/planners/aorrtc_settings.hh>
#include <vamp/planning/planners/grrtstar.hh>
#include <vamp/planning/planners/grrtstar_settings.hh>
#include <vamp/planning/planners/rrtc.hh>
#include <vamp/planning/planners/rrtc_settings.hh>
#include <vamp/planning/plan.hh>
#include <vamp/planning/simplify.hh>
#include <vamp/planning/simplify_settings.hh>
#include <vamp/random/halton.hh>
#include <vamp/random/rng.hh>
#include <vamp/utils.hh>
#include <vamp/vector.hh>

#if defined(__x86_64__)
#include <vamp/random/xorshift.hh>
#endif

#include <nanobind/nanobind.h>

// Not every ParameterizedSpace needs a "mid pose" concept: it exists for bimanual/
// mobile-base spaces (e.g. RBY1, whose t_mid_left/t_mid_right hand offsets are derived
// from a reference whole-body configuration) but not single-arm ones (e.g. IiwaMarker,
// whose eef pose IS the task-space pose already). Detected via SFINAE so
// ParameterizedSpaceTraits::compute_mid_pose and its binding can each stay a no-op for
// robots without it, rather than hard-erroring at compile time.
VAMP_DEFINE_HAS_METHOD(compute_mid_pose)

// LeaderFollowerSpace's counterpart of compute_mid_pose: derives a single fixed
// leader-to-follower hand offset (rel_pose) from a reference whole-body configuration,
// instead of a shared mid-frame offset. See BimanualIiwa::LeaderFollowerSpace::rel_pose.
VAMP_DEFINE_HAS_METHOD(compute_rel_pose)

// GCP (self-motion-manifold branch selector) is RBY1-specific: each rainbow arm has its
// own (elbow_sel, shoulder_sel, wrist_sel) triple, set independently per arm via
// Space::set_gcp(left, right). BimanualIiwa::ParameterizedSpace has the same two-triple
// shape under a different name (set_gc(left, right)) -- see has_set_gc_v below.
VAMP_DEFINE_HAS_METHOD(set_gcp)

// Single-triple self-motion-manifold branch selector, set via Space::set_smm(gc) --
// IiwaMarker's and BimanualIiwa::LeaderFollowerSpace's shape (one arm's IK, one triple),
// distinct from the two-triple set_gcp/set_gc bimanual shape above.
VAMP_DEFINE_HAS_METHOD(set_smm)

// BimanualIiwa::ParameterizedSpace's two-triple counterpart of set_gcp; see set_gcp's
// comment above for why this isn't unified with it (different method name, same shape).
VAMP_DEFINE_HAS_METHOD(set_gc)

// Target GCP branch a ConstrainedLocalPlanner-based (i.e. non-task-space) planner should be
// restricted to -- see ConstraintSettings::fix_single_smm and
// RBY1::ParameterizedSpace::set_target_smm/target_smm_left/target_smm_right. Distinct from
// set_gcp above (which resolve_block itself reads while IK-resolving a task-space state):
// this is read only by classify_smm_block/smm_mask_block, for a planner that never touches
// resolve_block or ParameterizedSpace at all.
VAMP_DEFINE_HAS_METHOD(set_target_smm)

// Detects LeaderFollowerSpace's rel_pose data member directly (decltype(T::rel_pose) is
// well-formed for a static data member exactly like it is for a static method), so a
// literal offset can be assigned in place -- for problems (e.g. a rigid dual-arm carry)
// that specify the fixed leader-to-follower offset directly instead of deriving it from
// a reference whole-body pose via compute_rel_pose.
VAMP_DEFINE_HAS_METHOD(rel_pose)

// Torso/free-joint feasibility search (RBY1-specific -- see ParameterizedSpace's
// torso_free_loss_jacobian / solve_torso_for_mid_pose_gradient_descent / _lm_inner in
// rby1.hh, generated by cricket's derive_rby1_parameterized_traces /
// RainbowConstrainedBimanualIkCG's `compute_gradient` mode). None of these three are
// templated (unlike classify_smm_block or the block solve variants below, which need the
// custom detail::has_X<Space, rake> pattern instead -- decltype() of a bare function-
// template name is ill-formed, see detail::has_eefs_collision_free's own comment), so
// VAMP_DEFINE_HAS_METHOD works directly, same as set_gcp above.
VAMP_DEFINE_HAS_METHOD(torso_free_loss_jacobian)
VAMP_DEFINE_HAS_METHOD(solve_torso_for_mid_pose_gradient_descent)
VAMP_DEFINE_HAS_METHOD(solve_torso_for_mid_pose_lm_inner)

// Independent (unconstrained) counterpart of the above: both hand targets are ordinary,
// independent poses (RainbowIkCG) instead of derived from a shared mid-pose plus fixed
// per-arm offsets -- see Space::independent_loss_jacobian /
// solve_torso_for_independent_poses_gradient_descent / _lm_inner in rby1.hh, generated by
// cricket's derive_rby1_parameterized_traces / RainbowIkCG's `compute_gradient` mode. Same
// "none of these three are templated" reasoning as the torso_free_* macros above.
VAMP_DEFINE_HAS_METHOD(independent_loss_jacobian)
VAMP_DEFINE_HAS_METHOD(solve_torso_for_independent_poses_gradient_descent)
VAMP_DEFINE_HAS_METHOD(solve_torso_for_independent_poses_lm_inner)

namespace vamp::binding
{
    static constexpr const std::size_t rake = vamp::FloatVectorWidth;

    namespace detail
    {
        // Detects whether Space exposes a templated eefs_collision_free<rake>(environment,
        // block) utility. Present on ParameterizedSpace/RBY1/IiwaMarker, but not required --
        // it's an IK-free prefilter never called by ParameterizedLocalPlanner itself (see
        // parameterized_local_planner.hh's resolve_and_check_impl, where the equivalent call
        // is commented out), only by the eefs_collision_free() python binding below. Spaces
        // without one (e.g. BimanualIiwa::LeaderFollowerSpace) simply don't expose that
        // prefilter to python; planning is unaffected.
        template <typename Space, std::size_t r, typename = void>
        struct has_eefs_collision_free : std::false_type
        {
        };

        template <typename Space, std::size_t r>
        struct has_eefs_collision_free<
            Space,
            r,
            std::void_t<decltype(Space::template eefs_collision_free<r>(
                std::declval<const vamp::collision::Environment<vamp::FloatVector<r>> &>(),
                std::declval<const typename Space::template StateBlock<r> &>()))>> : std::true_type
        {
        };

        // Detects whether Space exposes a templated
        // classify_smm_block<r>(Ambient::ConfigurationBlock<r>) utility (currently only
        // RBY1::ParameterizedSpace -- see its classify_smm_block/smm_mask_block and
        // ConstraintSettings::fix_single_smm). A plain VAMP_DEFINE_HAS_METHOD doesn't work
        // here since classify_smm_block is a template member: decltype(T::classify_smm_block)
        // alone (no template argument) is ill-formed for an unresolved function template, so
        // it needs the same explicit-instantiation SFINAE pattern as has_eefs_collision_free
        // above rather than the macro.
        template <typename Space, std::size_t r, typename = void>
        struct has_classify_smm : std::false_type
        {
        };

        template <typename Space, std::size_t r>
        struct has_classify_smm<
            Space,
            r,
            std::void_t<decltype(Space::template classify_smm_block<r>(std::declval<
                const typename Space::Ambient::template ConfigurationBlock<r> &>()))>>
            : std::true_type
        {
        };

        // Detects Space::solve_torso_for_mid_pose_block_gradient_descent<r>(...) -- RBY1-only,
        // the block/FloatVector counterpart of solve_torso_for_mid_pose_gradient_descent
        // (VAMP_DEFINE_HAS_METHOD above). solve_torso_for_mid_pose_block_lm_inner<r> always
        // exists alongside it (both come from the same fk_template.hh code path), so one
        // detector covers both.
        template <typename Space, std::size_t r, typename = void>
        struct has_torso_free_search_block : std::false_type
        {
        };

        template <typename Space, std::size_t r>
        struct has_torso_free_search_block<
            Space,
            r,
            std::void_t<decltype(Space::template solve_torso_for_mid_pose_block_gradient_descent<r>(
                std::declval<const std::array<std::array<float, 6>, r> &>(),
                std::declval<const std::array<float, 7> &>(),
                std::declval<const std::array<float, r> &>(),
                std::declval<const std::array<float, r> &>()))>> : std::true_type
        {
        };

        // Detects Space::solve_torso_for_independent_poses_block_gradient_descent<r>(...) --
        // RBY1-only, the block/FloatVector counterpart of
        // solve_torso_for_independent_poses_gradient_descent (VAMP_DEFINE_HAS_METHOD above).
        // Same reasoning as has_torso_free_search_block above -- one detector covers both
        // _gradient_descent and _lm_inner since they come from the same fk_template.hh code
        // path -- except the goal is two independent poses (left_pose, right_pose), not one
        // shared t_mid_pose.
        template <typename Space, std::size_t r, typename = void>
        struct has_independent_search_block : std::false_type
        {
        };

        template <typename Space, std::size_t r>
        struct has_independent_search_block<
            Space,
            r,
            std::void_t<decltype(Space::template solve_torso_for_independent_poses_block_gradient_descent<r>(
                std::declval<const std::array<std::array<float, 6>, r> &>(),
                std::declval<const std::array<float, 7> &>(),
                std::declval<const std::array<float, 7> &>(),
                std::declval<const std::array<float, r> &>(),
                std::declval<const std::array<float, r> &>()))>> : std::true_type
        {
        };
    }  // namespace detail

    // Traits for planning over Robot::ParameterizedSpace: a task-space parameterization
    // that IK-resolves into Robot's own ambient Configuration space. Mirrors the shape of
    // StaticRobotTraits (robot_helper.hh) closely enough to reuse bind_path_class,
    // bind_path_io, bind_planning_result, and bind_sampler from api_binder.hh unmodified,
    // but only supports the local-planner-aware planners (rrtc/aorrtc/grrtstar) -- PRM/FCIT
    // don't take a local planner and so can't resolve task-space states into the ambient
    // robot.
    template <
        typename Robot,
        typename SpaceT = typename Robot::ParameterizedSpace,
        typename Input = SpaceNDArrayInput<Robot, SpaceT>>
    struct ParameterizedSpaceTraits
    {
        using RobotType = Robot;
        using Space = SpaceT;
        using Ambient = typename Space::Ambient;

        using Cfg = typename Input::Type;
        using Pth = std::vector<Cfg>;
        using Path = vamp::planning::Path<Robot, Space>;
        using PlanningResult = vamp::planning::PlanningResult<Robot, Space>;
        using Sampler = vamp::rng::RNG<Robot, Space>;
        using Env = vamp::collision::Environment<float>;
        using EnvVec = vamp::collision::Environment<vamp::FloatVector<rake>>;

        using Configuration = typename Space::State;
        using RNG = vamp::rng::RNG<Robot, Space>;
        using LocalPlanner =
            vamp::planning::constraint::ParameterizedLocalPlanner<Robot, rake, Robot::resolution, Space>;

        // Explicit specialization of a nested member template isn't legal while the
        // enclosing ParameterizedSpaceTraits is still a template, so pick the planner type
        // via std::conditional_t instead of a specialized helper struct.
        template <vamp::planning::Planner P>
        using TaskPlannerT = std::conditional_t<
            P == vamp::planning::Planner::RRTC,
            vamp::planning::RRTC<Robot, rake, Robot::resolution, Space>,
            std::conditional_t<
                P == vamp::planning::Planner::AORRTC,
                vamp::planning::AORRTC<Robot, rake, Robot::resolution, Space>,
                vamp::planning::GRRTStar<Robot, rake, Robot::resolution, Space>>>;

        template <vamp::planning::Planner P, typename Settings>
        static auto solve_single(
            const Cfg &start,
            const Cfg &goal,
            const Env &env,
            const Settings &s,
            std::shared_ptr<Sampler> rng) -> PlanningResult
        {
            return TaskPlannerT<P>::template solve<LocalPlanner>(
                Input::to(start), Input::to(goal), EnvVec(env), s, rng, LocalPlanner());
        }

        template <vamp::planning::Planner P, typename Settings>
        static auto solve_multi(
            const Cfg &start,
            const Pth &goals,
            const Env &env,
            const Settings &s,
            std::shared_ptr<Sampler> rng) -> PlanningResult
        {
            std::vector<Configuration> goals_v;
            goals_v.reserve(goals.size());
            for (const auto &g : goals)
            {
                goals_v.emplace_back(Input::to(g));
            }

            return TaskPlannerT<P>::template solve<LocalPlanner>(
                Input::to(start), goals_v, EnvVec(env), s, rng, LocalPlanner());
        }

        // Distinct from the ambient robot's simplify() (which takes SimplifySettings and runs
        // the full bspline/reduce/perturb pipeline): this wraps the raw shortcut_path the
        // task-space demo uses, taking ShortcutSettings. Mutates path in place.
        static auto shortcut(
            Path &path,
            const Env &env,
            const vamp::planning::ShortcutSettings &settings) -> bool
        {
            return vamp::planning::shortcut_path<Robot, rake, Robot::resolution, LocalPlanner, Space>(
                path, EnvVec(env), settings, LocalPlanner());
        }

        // IK-resolve a single task-space state into the ambient robot's Configuration.
        // Returns (valid, ambient_configuration); does not collision-check the result --
        // callers that need that should follow up with the ambient robot's validate().
        //
        // Returns a plain std::array<float, Ambient::dimension> rather than
        // Ambient::ConfigurationArray: nanobind's std::array caster (nanobind/stl/array.h)
        // is specialized on std::array<Type, Size> exactly, and ConfigurationArray -- a
        // struct that derives from std::array<FloatT, dimension> to carry alignas -- is a
        // distinct type nanobind has no caster for, so returning it directly makes this
        // uncallable from python ("Unable to convert function return value to a Python
        // type!") despite compiling and generating a signature. Both are the same bytes,
        // so this is a lossless conversion.
        static auto resolve(const Cfg &state) -> std::pair<bool, std::array<float, Ambient::dimension>>
        {
            const auto s = Input::to(state);
            typename Space::template StateBlock<rake> block;
            for (std::size_t i = 0; i < Space::dimension; ++i)
            {
                block[i] = s.broadcast(i);
            }

            auto [valid, ambient_block] = Space::template resolve_block<rake>(block);

            std::array<float, Ambient::dimension> ambient;
            for (std::size_t i = 0; i < Ambient::dimension; ++i)
            {
                ambient[i] = ambient_block[{i, 0}];
            }

            return {valid, ambient};
        }

        // IK-free prefilter: hand geometry (+ any attachments) vs. environment/each other.
        // Not a substitute for a full collision check on the resolved ambient configuration.
        // Only present on spaces with an eefs_collision_free concept; see
        // detail::has_eefs_collision_free above.
        static auto eefs_collision_free(const Cfg &state, const Env &env) -> bool
        {
            if constexpr (detail::has_eefs_collision_free<Space, rake>::value)
            {
                const auto s = Input::to(state);
                typename Space::template StateBlock<rake> block;
                for (std::size_t i = 0; i < Space::dimension; ++i)
                {
                    block[i] = s.broadcast(i);
                }

                return Space::template eefs_collision_free<rake>(EnvVec(env), block);
            }
            else
            {
                (void) state;
                (void) env;
                throw std::runtime_error("this task space has no eefs_collision_free concept");
            }
        }

        // Derive t_mid_left/t_mid_right (thread-local to Space) from a reference whole-body
        // ambient configuration; the normal way to set them before planning. Only present
        // on spaces with a mid-pose concept (e.g. RBY1); see has_compute_mid_pose_v above.
        // The binder (parameterized_space_binder.hh) only exposes this to python when the
        // if constexpr branch below is taken, so the else branch is unreachable in
        // practice -- it exists only so this method stays well-formed to reference (e.g.
        // take the address of) for spaces without compute_mid_pose.
        //
        // Takes a plain std::array<float, Ambient::dimension> rather than
        // Ambient::ConfigurationArray for the same reason resolve() returns one instead
        // of the latter -- see the comment there.
        static void compute_mid_pose(const std::array<float, Ambient::dimension> &ambient)
        {
            if constexpr (has_compute_mid_pose_v<Space>)
            {
                typename Ambient::ConfigurationArray q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = ambient[i];
                }
                Space::compute_mid_pose(q);
            }
            else
            {
                (void) ambient;
                throw std::runtime_error("this task space has no mid-pose concept");
            }
        }

        // Derive rel_pose (thread-local to Space) from a reference whole-body ambient
        // configuration; LeaderFollowerSpace's counterpart of compute_mid_pose. Only
        // present on spaces with a compute_rel_pose concept; see has_compute_rel_pose_v
        // above. Same nanobind-caster rationale as compute_mid_pose for the plain
        // std::array<float, Ambient::dimension> parameter.
        static void compute_rel_pose(const std::array<float, Ambient::dimension> &ambient)
        {
            if constexpr (has_compute_rel_pose_v<Space>)
            {
                typename Ambient::ConfigurationArray q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = ambient[i];
                }
                Space::compute_rel_pose(q);
            }
            else
            {
                (void) ambient;
                throw std::runtime_error("this task space has no rel-pose concept");
            }
        }

        // Directly overwrite rel_pose (thread-local to Space) with a caller-supplied fixed
        // (x, y, z, qx, qy, qz, qw) leader-to-follower offset, bypassing compute_rel_pose's
        // FK derivation. Only present on spaces with a rel_pose member; see has_rel_pose_v
        // above.
        static void set_rel_pose(const std::array<float, 7> &pose)
        {
            if constexpr (has_rel_pose_v<Space>)
            {
                Space::rel_pose = pose;
            }
            else
            {
                (void) pose;
                throw std::runtime_error("this task space has no rel_pose concept");
            }
        }

        // Overwrite the static-stability support polygon LocalPlanner checks the resolved
        // ambient center of mass against (see ParameterizedLocalPlanner::set_support_polygon).
        // Only meaningful on spaces with a compute_com utility (e.g. RBY1); on spaces without
        // one, com_within_support_polygon is a no-op (always true) regardless of what the
        // polygon is set to, so the binder (parameterized_space_binder.hh) doesn't expose this
        // at all rather than expose a setter with no effect. Same has_compute_com<Space, rake>
        // gate ParameterizedLocalPlanner::com_within_support_polygon itself uses.
        static void set_support_polygon(const std::vector<std::array<float, 2>> &polygon_xy)
        {
            if constexpr (vamp::planning::constraint::detail::has_compute_com<Space, rake>::value)
            {
                LocalPlanner::set_support_polygon(polygon_xy);
            }
            else
            {
                (void) polygon_xy;
                throw std::runtime_error("this task space has no center-of-mass/support-polygon concept");
            }
        }

        // Set the GCP (elbow/shoulder/wrist self-motion-manifold branch) selector shared by
        // every lane -- the "many task-space states, one shared branch" mode
        // ParameterizedLocalPlanner/resolve_and_check use while extending the tree, where
        // the whole planning problem is meant to stay on a single branch. `left`/`right`
        // are each (elbow_sel, shoulder_sel, wrist_sel), matching Space::set_gcp. Only
        // present on spaces with a GCP concept (currently RBY1); see has_set_gcp_v above.
        static void set_gcp(const std::array<float, 3> &left, const std::array<float, 3> &right)
        {
            if constexpr (has_set_gcp_v<Space>)
            {
                Space::set_gcp(left, right);
            }
            else
            {
                (void) left;
                (void) right;
                throw std::runtime_error("this task space has no GCP (self-motion-manifold branch) concept");
            }
        }

        // Two-triple counterpart of set_gcp, for spaces that name it set_gc instead (e.g.
        // BimanualIiwa::ParameterizedSpace). Only present on spaces with a set_gc concept;
        // see has_set_gc_v above.
        static void set_gc(const std::array<float, 3> &left, const std::array<float, 3> &right)
        {
            if constexpr (has_set_gc_v<Space>)
            {
                Space::set_gc(left, right);
            }
            else
            {
                (void) left;
                (void) right;
                throw std::runtime_error("this task space has no set_gc (self-motion-manifold branch) concept");
            }
        }

        // Set the single-triple self-motion-manifold branch selector shared by every lane
        // (e.g. IiwaMarker's and BimanualIiwa::LeaderFollowerSpace's smm). Only present on
        // spaces with a set_smm concept; see has_set_smm_v above.
        static void set_smm(const std::array<float, 3> &gc)
        {
            if constexpr (has_set_smm_v<Space>)
            {
                Space::set_smm(gc);
            }
            else
            {
                (void) gc;
                throw std::runtime_error("this task space has no set_smm (self-motion-manifold branch) concept");
            }
        }

        // Recovers (elbow_sel, shoulder_sel, wrist_sel) per arm from an already-resolved
        // whole-body ambient configuration alone -- for a ConstrainedLocalPlanner-based
        // planner (e.g. RBY1's projection-based mcvamp planner), which never goes through
        // resolve_block/ParameterizedSpace and so has no GCP already lying around to read.
        // Also used to lock a torso-free-search call (see below) onto the SAME branch an
        // existing configuration is already on -- that search only moves within a fixed
        // branch, see RainbowConstrainedBimanualIkCG's header comment in cricket's
        // rainbow_ik_cg.hh. Only present on spaces with a classify_smm_block concept; see
        // detail::has_classify_smm above. Takes a plain
        // std::array<float, Ambient::dimension> rather than Ambient::ConfigurationArray for
        // the same nanobind-caster reason compute_mid_pose does -- see that method's
        // comment.
        static auto classify_smm(const std::array<float, Ambient::dimension> &ambient)
            -> std::pair<std::array<float, 3>, std::array<float, 3>>
        {
            if constexpr (detail::has_classify_smm<Space, rake>::value)
            {
                typename Ambient::ConfigurationArray q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = ambient[i];
                }
                typename Ambient::Configuration cfg(q);

                typename Ambient::template ConfigurationBlock<rake> block;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    block[i] = cfg.broadcast(i);
                }

                const auto classified = Space::template classify_smm_block<rake>(block);
                return {
                    {classified[0][0][{0, 0}], classified[0][1][{0, 0}], classified[0][2][{0, 0}]},
                    {classified[1][0][{0, 0}], classified[1][1][{0, 0}], classified[1][2][{0, 0}]}};
            }
            else
            {
                (void) ambient;
                throw std::runtime_error(
                    "this task space has no SMM classify (self-motion-manifold branch) concept");
            }
        }

        // ---------------------------------------------------------------------------
        // Torso/free-joint feasibility search (RBY1-specific -- see
        // has_torso_free_loss_jacobian_v etc. above for what gates each method here). Every
        // struct returned below is this Traits' OWN plain-aggregate type
        // (TorsoFreeLossJacobianResult / TorsoFreeSolveResultPy / TorsoFreeSolveBlockResultPy),
        // not Space's own TorsoFreeLossJacobian / TorsoFreeSolveResult /
        // TorsoFreeSolveBlockResult<rake> -- those carry an Ambient::ConfigurationArray field,
        // which (like resolve()'s own ambient_configuration) nanobind has no caster for;
        // converted here to a plain std::array<float, Ambient::dimension>, same reasoning as
        // resolve()'s own comment above. `max_iters`/`step_size`/`tol` have no defaults here --
        // the binder (parameterized_space_binder.hh) supplies them at the .def(...) call site,
        // same convention as shortcut()'s "settings"_a = vp_::ShortcutSettings{}.
        // ---------------------------------------------------------------------------

        struct TorsoFreeLossJacobianResult
        {
            bool feasible;
            std::array<float, Ambient::dimension> q;
            float loss_left;
            float loss_right;
            std::array<float, 8> jac_left;
            std::array<float, 8> jac_right;
        };

        static auto torso_free_loss_jacobian(
            const std::array<float, 6> &torso,
            const std::array<float, 7> &t_mid_pose,
            float psi_left,
            float psi_right) -> TorsoFreeLossJacobianResult
        {
            if constexpr (has_torso_free_loss_jacobian_v<Space>)
            {
                const auto r = Space::torso_free_loss_jacobian(torso, t_mid_pose, psi_left, psi_right);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {r.feasible, q, r.loss_left, r.loss_right, r.jac_left, r.jac_right};
            }
            else
            {
                (void) torso;
                (void) t_mid_pose;
                (void) psi_left;
                (void) psi_right;
                throw std::runtime_error("this task space has no torso-free-search concept");
            }
        }

        struct TorsoFreeSolveResultPy
        {
            bool converged;
            std::array<float, Ambient::dimension> q;
            std::array<float, 6> torso;
            float psi_left;
            float psi_right;
            float loss_left;
            float loss_right;
            std::size_t iterations;
        };

        static auto solve_torso_for_mid_pose_gradient_descent(
            const std::array<float, 6> &torso_init,
            const std::array<float, 7> &t_mid_pose,
            float psi_left_init,
            float psi_right_init,
            std::size_t max_iters,
            float step_size,
            float tol) -> TorsoFreeSolveResultPy
        {
            if constexpr (has_solve_torso_for_mid_pose_gradient_descent_v<Space>)
            {
                const auto r = Space::solve_torso_for_mid_pose_gradient_descent(
                    torso_init, t_mid_pose, psi_left_init, psi_right_init, max_iters, step_size, tol);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {r.converged, q, r.torso, r.psi_left, r.psi_right, r.loss_left, r.loss_right, r.iterations};
            }
            else
            {
                (void) torso_init;
                (void) t_mid_pose;
                (void) psi_left_init;
                (void) psi_right_init;
                (void) max_iters;
                (void) step_size;
                (void) tol;
                throw std::runtime_error("this task space has no torso-free-search concept");
            }
        }

        static auto solve_torso_for_mid_pose_lm_inner(
            const std::array<float, 6> &torso_init,
            const std::array<float, 7> &t_mid_pose,
            float psi_left_init,
            float psi_right_init,
            std::size_t max_iters,
            float step_size,
            float tol) -> TorsoFreeSolveResultPy
        {
            if constexpr (has_solve_torso_for_mid_pose_lm_inner_v<Space>)
            {
                const auto r = Space::solve_torso_for_mid_pose_lm_inner(
                    torso_init, t_mid_pose, psi_left_init, psi_right_init, max_iters, step_size, tol);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {r.converged, q, r.torso, r.psi_left, r.psi_right, r.loss_left, r.loss_right, r.iterations};
            }
            else
            {
                (void) torso_init;
                (void) t_mid_pose;
                (void) psi_left_init;
                (void) psi_right_init;
                (void) max_iters;
                (void) step_size;
                (void) tol;
                throw std::runtime_error("this task space has no torso-free-search concept");
            }
        }

        // Block/FloatVector counterpart: rake attempts at once, one entry per lane in
        // torso_inits/psi_left_inits/psi_right_inits, stopping as soon as any lane converges.
        // The random sampling of lanes 1..rake-1 (lane 0 conventionally {0,0,0,0,0,0}/0/0) is
        // the CALLER's job (python or otherwise) -- see
        // Space::solve_torso_for_mid_pose_block_impl's header comment in fk_template.hh for
        // why that sampling doesn't live in generated code either.
        struct TorsoFreeSolveBlockResultPy
        {
            bool converged;
            std::size_t lane;
            std::array<float, Ambient::dimension> q;
            std::array<float, 6> torso;
            float psi_left;
            float psi_right;
            float loss_left;
            float loss_right;
            std::size_t iterations;
        };

        static auto solve_torso_for_mid_pose_block_gradient_descent(
            const std::array<std::array<float, 6>, rake> &torso_inits,
            const std::array<float, 7> &t_mid_pose,
            const std::array<float, rake> &psi_left_inits,
            const std::array<float, rake> &psi_right_inits,
            std::size_t max_iters,
            float step_size,
            float tol) -> TorsoFreeSolveBlockResultPy
        {
            if constexpr (detail::has_torso_free_search_block<Space, rake>::value)
            {
                const auto r = Space::template solve_torso_for_mid_pose_block_gradient_descent<rake>(
                    torso_inits, t_mid_pose, psi_left_inits, psi_right_inits, max_iters, step_size, tol);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {
                    r.converged, r.lane, q, r.torso, r.psi_left, r.psi_right, r.loss_left, r.loss_right,
                    r.iterations};
            }
            else
            {
                (void) torso_inits;
                (void) t_mid_pose;
                (void) psi_left_inits;
                (void) psi_right_inits;
                (void) max_iters;
                (void) step_size;
                (void) tol;
                throw std::runtime_error("this task space has no block torso-free-search concept");
            }
        }

        static auto solve_torso_for_mid_pose_block_lm_inner(
            const std::array<std::array<float, 6>, rake> &torso_inits,
            const std::array<float, 7> &t_mid_pose,
            const std::array<float, rake> &psi_left_inits,
            const std::array<float, rake> &psi_right_inits,
            std::size_t max_iters,
            float step_size,
            float tol) -> TorsoFreeSolveBlockResultPy
        {
            if constexpr (detail::has_torso_free_search_block<Space, rake>::value)
            {
                const auto r = Space::template solve_torso_for_mid_pose_block_lm_inner<rake>(
                    torso_inits, t_mid_pose, psi_left_inits, psi_right_inits, max_iters, step_size, tol);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {
                    r.converged, r.lane, q, r.torso, r.psi_left, r.psi_right, r.loss_left, r.loss_right,
                    r.iterations};
            }
            else
            {
                (void) torso_inits;
                (void) t_mid_pose;
                (void) psi_left_inits;
                (void) psi_right_inits;
                (void) max_iters;
                (void) step_size;
                (void) tol;
                throw std::runtime_error("this task space has no block torso-free-search concept");
            }
        }

        // ---------------------------------------------------------------------------
        // Independent (unconstrained) bimanual counterpart of the torso-free search above:
        // same shape, but each hand's goal pose is an ordinary, independent argument
        // (left_pose/right_pose) instead of being derived from a shared t_mid_pose plus
        // fixed per-arm offsets -- no compute_mid_pose() call is needed before using this.
        // Same "own plain-aggregate result type" reasoning as TorsoFreeLossJacobianResult
        // etc. above.
        // ---------------------------------------------------------------------------

        struct IndependentLossJacobianResult
        {
            bool feasible;
            std::array<float, Ambient::dimension> q;
            float loss_left;
            float loss_right;
            std::array<float, 8> jac_left;
            std::array<float, 8> jac_right;
        };

        static auto independent_loss_jacobian(
            const std::array<float, 6> &torso,
            const std::array<float, 7> &left_pose,
            const std::array<float, 7> &right_pose,
            float left_j15,
            float right_j24) -> IndependentLossJacobianResult
        {
            if constexpr (has_independent_loss_jacobian_v<Space>)
            {
                const auto r = Space::independent_loss_jacobian(torso, left_pose, right_pose, left_j15, right_j24);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {r.feasible, q, r.loss_left, r.loss_right, r.jac_left, r.jac_right};
            }
            else
            {
                (void) torso;
                (void) left_pose;
                (void) right_pose;
                (void) left_j15;
                (void) right_j24;
                throw std::runtime_error("this task space has no independent-pose torso-free-search concept");
            }
        }

        struct IndependentSolveResultPy
        {
            bool converged;
            std::array<float, Ambient::dimension> q;
            std::array<float, 6> torso;
            float left_j15;
            float right_j24;
            float loss_left;
            float loss_right;
            std::size_t iterations;
        };

        static auto solve_torso_for_independent_poses_gradient_descent(
            const std::array<float, 6> &torso_init,
            const std::array<float, 7> &left_pose,
            const std::array<float, 7> &right_pose,
            float left_j15_init,
            float right_j24_init,
            std::size_t max_iters,
            float step_size,
            float tol) -> IndependentSolveResultPy
        {
            if constexpr (has_solve_torso_for_independent_poses_gradient_descent_v<Space>)
            {
                const auto r = Space::solve_torso_for_independent_poses_gradient_descent(
                    torso_init, left_pose, right_pose, left_j15_init, right_j24_init, max_iters, step_size, tol);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {r.converged, q, r.torso, r.left_j15, r.right_j24, r.loss_left, r.loss_right, r.iterations};
            }
            else
            {
                (void) torso_init;
                (void) left_pose;
                (void) right_pose;
                (void) left_j15_init;
                (void) right_j24_init;
                (void) max_iters;
                (void) step_size;
                (void) tol;
                throw std::runtime_error("this task space has no independent-pose torso-free-search concept");
            }
        }

        static auto solve_torso_for_independent_poses_lm_inner(
            const std::array<float, 6> &torso_init,
            const std::array<float, 7> &left_pose,
            const std::array<float, 7> &right_pose,
            float left_j15_init,
            float right_j24_init,
            std::size_t max_iters,
            float step_size,
            float tol) -> IndependentSolveResultPy
        {
            if constexpr (has_solve_torso_for_independent_poses_lm_inner_v<Space>)
            {
                const auto r = Space::solve_torso_for_independent_poses_lm_inner(
                    torso_init, left_pose, right_pose, left_j15_init, right_j24_init, max_iters, step_size, tol);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {r.converged, q, r.torso, r.left_j15, r.right_j24, r.loss_left, r.loss_right, r.iterations};
            }
            else
            {
                (void) torso_init;
                (void) left_pose;
                (void) right_pose;
                (void) left_j15_init;
                (void) right_j24_init;
                (void) max_iters;
                (void) step_size;
                (void) tol;
                throw std::runtime_error("this task space has no independent-pose torso-free-search concept");
            }
        }

        // Block/FloatVector counterpart: rake attempts at once, one entry per lane in
        // torso_inits/left_j15_inits/right_j24_inits, for the SAME pair of goal poses --
        // same sampling-is-the-caller's-job convention as
        // solve_torso_for_mid_pose_block_gradient_descent above.
        struct IndependentSolveBlockResultPy
        {
            bool converged;
            std::size_t lane;
            std::array<float, Ambient::dimension> q;
            std::array<float, 6> torso;
            float left_j15;
            float right_j24;
            float loss_left;
            float loss_right;
            std::size_t iterations;
        };

        static auto solve_torso_for_independent_poses_block_gradient_descent(
            const std::array<std::array<float, 6>, rake> &torso_inits,
            const std::array<float, 7> &left_pose,
            const std::array<float, 7> &right_pose,
            const std::array<float, rake> &left_j15_inits,
            const std::array<float, rake> &right_j24_inits,
            std::size_t max_iters,
            float step_size,
            float tol) -> IndependentSolveBlockResultPy
        {
            if constexpr (detail::has_independent_search_block<Space, rake>::value)
            {
                const auto r = Space::template solve_torso_for_independent_poses_block_gradient_descent<rake>(
                    torso_inits, left_pose, right_pose, left_j15_inits, right_j24_inits, max_iters, step_size, tol);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {
                    r.converged, r.lane, q, r.torso, r.left_j15, r.right_j24, r.loss_left, r.loss_right,
                    r.iterations};
            }
            else
            {
                (void) torso_inits;
                (void) left_pose;
                (void) right_pose;
                (void) left_j15_inits;
                (void) right_j24_inits;
                (void) max_iters;
                (void) step_size;
                (void) tol;
                throw std::runtime_error("this task space has no block independent-pose torso-free-search concept");
            }
        }

        static auto solve_torso_for_independent_poses_block_lm_inner(
            const std::array<std::array<float, 6>, rake> &torso_inits,
            const std::array<float, 7> &left_pose,
            const std::array<float, 7> &right_pose,
            const std::array<float, rake> &left_j15_inits,
            const std::array<float, rake> &right_j24_inits,
            std::size_t max_iters,
            float step_size,
            float tol) -> IndependentSolveBlockResultPy
        {
            if constexpr (detail::has_independent_search_block<Space, rake>::value)
            {
                const auto r = Space::template solve_torso_for_independent_poses_block_lm_inner<rake>(
                    torso_inits, left_pose, right_pose, left_j15_inits, right_j24_inits, max_iters, step_size, tol);

                std::array<float, Ambient::dimension> q;
                for (std::size_t i = 0; i < Ambient::dimension; ++i)
                {
                    q[i] = r.q[i];
                }

                return {
                    r.converged, r.lane, q, r.torso, r.left_j15, r.right_j24, r.loss_left, r.loss_right,
                    r.iterations};
            }
            else
            {
                (void) torso_inits;
                (void) left_pose;
                (void) right_pose;
                (void) left_j15_inits;
                (void) right_j24_inits;
                (void) max_iters;
                (void) step_size;
                (void) tol;
                throw std::runtime_error("this task space has no block independent-pose torso-free-search concept");
            }
        }

        // Set the target GCP branch (elbow_sel, shoulder_sel, wrist_sel per arm) a
        // ConstrainedLocalPlanner-based planner (ConstraintSettings::fix_single_smm) must stay
        // on -- typically the result of classify_smm() applied to a planning problem's own
        // start configuration ("stay on whatever branch the start is already on"). Only
        // present on spaces with a set_target_smm concept; see has_set_target_smm_v above.
        static void set_target_smm(const std::array<float, 3> &left, const std::array<float, 3> &right)
        {
            if constexpr (has_set_target_smm_v<Space>)
            {
                Space::set_target_smm(left, right);
            }
            else
            {
                (void) left;
                (void) right;
                throw std::runtime_error("this task space has no target-SMM concept");
            }
        }

        static auto make_halton() -> std::shared_ptr<Sampler>
        {
            return std::make_shared<vamp::rng::Halton<Robot, Space>>();
        }

        static auto make_xorshift(std::uint64_t seed) -> std::shared_ptr<Sampler>
        {
#if defined(__x86_64__)
            return (seed == 0) ? std::make_shared<vamp::rng::XORShift<Robot, Space>>() :
                                 std::make_shared<vamp::rng::XORShift<Robot, Space>>(seed, seed + 1);
#else
            throw std::runtime_error("XORShift is not supported on non-x86 systems!");
#endif
        }

        // Path element access (path_get/set/append/insert/numpy), for bind_path_class /
        // bind_path_io.
        static auto path_get(const Path &p, std::size_t i) -> Cfg
        {
            return Input::from(p[i]);
        }

        static void path_set(Path &p, std::size_t i, const Cfg &c)
        {
            p[i] = Input::to(c);
        }

        static void path_append(Path &p, const Cfg &c)
        {
            p.emplace_back(Input::to(c));
        }

        static void path_insert(Path &p, std::size_t i, const Cfg &c)
        {
            p.insert(p.begin() + static_cast<std::ptrdiff_t>(i), Input::to(c));
        }

        static auto path_numpy(const Path &p)
        {
            return make_ndarray_filled<2>(
                {p.size(), Space::dimension},
                [&](float *buf)
                {
                    for (std::size_t i = 0; i < p.size(); ++i)
                    {
                        auto arr = p[i].to_array();
                        for (std::size_t j = 0; j < Space::dimension; ++j)
                        {
                            buf[(i * Space::dimension) + j] = arr[j];
                        }
                    }
                });
        }

        static auto path_validate(Path &, const Env &) -> bool
        {
            // Path::validate only compiles for Space == Robot (see plan.hh); task-space path
            // validity goes through LocalPlanner::validate / resolve() + the ambient robot's
            // validate() instead.
            throw std::runtime_error(
                "path.validate() is not supported for a task-space Path; resolve() each "
                "waypoint and validate the ambient robot's configuration instead");
        }

        static auto result_solved(const PlanningResult &r) -> bool
        {
            return r.solved;
        }

        static void sampler_skip(Sampler &s, std::size_t n)
        {
            for (std::size_t i = 0; i < n; ++i)
            {
                s.next();
            }
        }

        static auto sampler_next(Sampler &s) -> Cfg
        {
            return Input::from(s.next());
        }
    };
}  // namespace vamp::binding
