<?xml version="1.0"?>
<package format="2">
  <name>rlbenchpanda_description</name>
  <version>0.0.0</version>
  <description>RLBench Panda Robot Description</description>
  <maintainer email="you@todo.todo">user</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <export>
  </export>
</package>