// Standalone smoke test for ParameterizedSpace::solve_torso_for_mid_pose_gradient_descent /
// solve_torso_for_mid_pose_lm_inner (rby1.hh, generated by cricket's
// derive_rby1_parameterized_traces / RainbowConstrainedBimanualIkCG's `compute_gradient` mode --
// see cricket's src/parameterization/rainbow_ik_cg.hh and resources/templates/fk_template.hh):
// differentiates the closed-form arm IK's feasibility loss back through the real
// base->torso forward kinematics, and does gradient-based search over
// [torso_0..5, psi_left, psi_right] (the wheeled base held fixed at the origin) to make a
// goal mid-pose reachable.
//
// For each of a handful of already-solved whole-body configurations logged by ruby's live
// planner (rby1-constrained-planning/vamp_rrtc_logs/rrtc_calls.jsonl -- q_start/q_goal, 24
// floats each, in Robot::dimension's own base(4) + torso(6) + left_arm(7) + right_arm(7)
// order), this:
//   1. computes ee_left/ee_right world poses from q_start via Robot::eefk,
//   2. derives the goal mid-pose T_mid the same way ParameterizedSpace::compute_mid_pose does
//      (translation midpoint of the two hands, identity rotation) in WORLD frame, then
//      re-expresses it in q_start's own BASE frame (base_x, base_y, base_rz) -- since the
//      solve below always treats the base as fixed at the origin, this is the frame its
//      T_mid input actually needs to be given in;
//   3. reads off q_start's own (elbow_sel, shoulder_sel, wrist_sel) GCP branch per arm via
//      ParameterizedSpace::classify_smm_block and locks the solve onto that same branch (the
//      solve searches torso/psi on a FIXED branch, not across branches -- see
//      RainbowConstrainedBimanualIkCG's header comment in rainbow_ik_cg.hh);
//   4. starting from torso = {0, 0, 0, 0, 0, 0} (per this test's whole point -- can the torso
//      be found from scratch, not just refined from the logged solution?) and an arbitrary
//      psi_left/psi_right = 0 guess, runs both solve_torso_for_mid_pose_gradient_descent and
//      solve_torso_for_mid_pose_lm_inner, reporting whether each converged, in how many
//      iterations, and how far the resulting hands ended up from the goal mid-pose.
//   5. does the same again, but with the block/FloatVector counterparts
//      (solve_torso_for_mid_pose_block_gradient_descent/_lm_inner): `rake` attempts at once,
//      lane 0 forced to the same {0,0,0,0,0,0}/0/0 starting point as step 4, the remaining
//      lanes randomly sampled (torso within its own joint limits, psi in [0, 2*pi)) -- the
//      sampling itself is this file's job, not fk_template.hh's (see that file's own header
//      comment on solve_torso_for_mid_pose_block_impl for why).
//
// Usage: vamp_rby1_compute_ik_test [path/to/rrtc_calls.jsonl] [num_examples]
//   Defaults to /src/rby1-constrained-planning/vamp_rrtc_logs/rrtc_calls.jsonl and 3 examples.

#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <iostream>
#include <random>
#include <string>
#include <utility>
#include <vector>

#include <Eigen/Geometry>
#include <nlohmann/json.hpp>

#include <vamp/robots/rby1.hh>
#include <vamp/vector.hh>

using Robot = vamp::robots::RBY1;
using ParameterizedSpace = Robot::ParameterizedSpace;
static constexpr const std::size_t rake = vamp::FloatVectorWidth;

namespace
{
    // Isometry -> (x, y, z, qx, qy, qz, qw), the pose layout every ParameterizedSpace tape
    // input/output (t_mid_pose, t_mid_left, t_mid_right, ...) uses -- same construction as
    // ParameterizedSpace::compute_mid_pose's own t_mid_left/t_mid_right assignment.
    auto to_pose_array(const Eigen::Isometry3f &pose) -> std::array<float, 7>
    {
        const Eigen::Quaternionf q(pose.rotation());
        return {
            pose.translation().x(), pose.translation().y(), pose.translation().z(),
            q.x(), q.y(), q.z(), q.w()};
    }

    // Loads up to `max_examples` "leg" (real reach-to-grasp problem, not a throwaway "probe"
    // feasibility check -- see rby1_mcvamp_planner.cc's extract_problem for the same filter)
    // entries with a 24-float q_start from a .jsonl log, one JSON object per line.
    auto load_q_starts(const std::string &path, std::size_t max_examples) -> std::vector<std::array<float, 24>>
    {
        std::ifstream input_file(path);
        if (not input_file)
        {
            throw std::runtime_error("Failed to open input jsonl file: " + path);
        }

        std::vector<std::array<float, 24>> q_starts;
        std::string line;
        while (q_starts.size() < max_examples and std::getline(input_file, line))
        {
            if (line.find_first_not_of(" \t\r\n") == std::string::npos)
            {
                continue;
            }

            const auto entry = nlohmann::json::parse(line);
            if (entry.value("kind", std::string()) != "leg")
            {
                continue;
            }
            if (not entry.value("solved", true))
            {
                continue;
            }
            if (not entry.contains("q_start"))
            {
                continue;
            }

            const auto q_start_vec = entry.at("q_start").get<std::vector<float>>();
            if (q_start_vec.size() != Robot::dimension)
            {
                continue;
            }

            std::array<float, 24> q_start{};
            std::copy(q_start_vec.begin(), q_start_vec.end(), q_start.begin());
            q_starts.push_back(q_start);
        }

        return q_starts;
    }

    // q_start's own (elbow_sel, shoulder_sel, wrist_sel) per arm, read off via
    // classify_smm_block -- the solve is locked onto this branch (see this file's header
    // comment) rather than searching across branches.
    auto classify_branch(const std::array<float, 24> &q_start)
        -> std::pair<std::array<float, 3>, std::array<float, 3>>
    {
        Robot::ConfigurationArray q_array{};
        std::copy(q_start.begin(), q_start.end(), q_array.begin());
        Robot::Configuration q_configuration(q_array);

        Robot::ConfigurationBlock<rake> q_block;
        for (std::size_t j = 0; j < Robot::dimension; ++j)
        {
            q_block[j] = q_configuration.broadcast(j);
        }

        const auto classified = ParameterizedSpace::classify_smm_block<rake>(q_block);

        std::array<float, 3> left{};
        std::array<float, 3> right{};
        for (std::size_t k = 0; k < 3; ++k)
        {
            left[k] = classified[0][k][{0, 0}];
            right[k] = classified[1][k][{0, 0}];
        }

        return {left, right};
    }

    // `rake` [torso, psi_left, psi_right] starting points for
    // solve_torso_for_mid_pose_block_*: lane 0 forced to {0,0,0,0,0,0}/0/0 (the same starting
    // point run_one_example's scalar solve uses), lanes 1..rake-1 drawn uniformly at random --
    // torso within Robot::lower_bound/upper_bound's own torso_0..5 slice (ambient indices
    // [4:10)), psi in [0, 2*pi). See fk_template.hh's solve_torso_for_mid_pose_block_impl
    // header comment for why this sampling lives here rather than in that file.
    struct BlockInits
    {
        std::array<std::array<float, 6>, rake> torso;
        std::array<float, rake> psi_left;
        std::array<float, rake> psi_right;
    };

    auto sample_block_inits(std::mt19937 &rng) -> BlockInits
    {
        static const float two_pi = 2.0F * std::acos(-1.0F);
        std::uniform_real_distribution<float> psi_dist(0.0F, two_pi);

        BlockInits inits{};
        inits.torso[0] = {0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F};
        inits.psi_left[0] = 0.0F;
        inits.psi_right[0] = 0.0F;

        for (std::size_t lane = 1; lane < rake; ++lane)
        {
            for (std::size_t j = 0; j < 6; ++j)
            {
                std::uniform_real_distribution<float> torso_dist(
                    Robot::lower_bound[4 + j], Robot::upper_bound[4 + j]);
                inits.torso[lane][j] = torso_dist(rng);
            }
            inits.psi_left[lane] = psi_dist(rng);
            inits.psi_right[lane] = psi_dist(rng);
        }

        return inits;
    }

    auto run_one_example(std::size_t index, const std::array<float, 24> &q_start, std::mt19937 &rng) -> void
    {
        std::cout << "\n=== example " << index << " ===" << std::endl;

        // Step 1: ee_left/ee_right world poses from q_start.
        const Eigen::Isometry3f ee_left_world = Robot::eefk(q_start, 0);
        const Eigen::Isometry3f ee_right_world = Robot::eefk(q_start, 1);

        // Step 2: goal mid-pose, world frame -- translation midpoint, identity rotation, same
        // construction as ParameterizedSpace::compute_mid_pose -- then re-expressed in
        // q_start's own base frame (base_x, base_y, base_rz from q_start[0:4)), since the
        // solve below always treats the base as fixed at the origin.
        Eigen::Isometry3f t_world_mid = Eigen::Isometry3f::Identity();
        t_world_mid.translation() =
            0.5F * (ee_left_world.translation() + ee_right_world.translation());

        const float base_rz = std::atan2(q_start[3], q_start[2]);
        Eigen::Isometry3f t_world_base = Eigen::Isometry3f::Identity();
        t_world_base.translation() = Eigen::Vector3f(q_start[0], q_start[1], 0.0F);
        t_world_base.linear() = Eigen::AngleAxisf(base_rz, Eigen::Vector3f::UnitZ()).toRotationMatrix();

        const Eigen::Isometry3f t_base_mid = t_world_base.inverse() * t_world_mid;
        const std::array<float, 7> t_mid_pose = to_pose_array(t_base_mid);

        std::cout << "  base pose (x, y, rz): (" << q_start[0] << ", " << q_start[1] << ", " << base_rz << ")"
                   << std::endl;
        std::cout << "  goal mid-pose (base frame): (" << t_mid_pose[0] << ", " << t_mid_pose[1] << ", "
                   << t_mid_pose[2] << ")" << std::endl;

        // Step 3: lock the solve onto q_start's own GCP branch.
        const auto [left_gcp, right_gcp] = classify_branch(q_start);
        ParameterizedSpace::set_gcp(left_gcp, right_gcp);
        std::cout << "  left_gcp: (" << left_gcp[0] << ", " << left_gcp[1] << ", " << left_gcp[2] << ")"
                   << ", right_gcp: (" << right_gcp[0] << ", " << right_gcp[1] << ", " << right_gcp[2] << ")"
                   << std::endl;

        // Step 4: solve from torso = 0, psi = 0 -- both solvers, reported side by side.
        const std::array<float, 6> torso_init = {0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F};
        constexpr float psi_left_init = 0.0F;
        constexpr float psi_right_init = 0.0F;

        auto report = [&](const std::string &label, const ParameterizedSpace::TorsoFreeSolveResult &result)
        {
            std::cout << "  [" << label << "] converged = " << std::boolalpha << result.converged
                       << ", iterations = " << result.iterations << ", loss_left = " << result.loss_left
                       << ", loss_right = " << result.loss_right << std::endl;
            std::cout << "  [" << label << "] torso = (";
            for (std::size_t i = 0; i < 6; ++i)
            {
                std::cout << result.torso[i] << (i + 1 < 6 ? ", " : "");
            }
            std::cout << "), psi_left = " << result.psi_left << ", psi_right = " << result.psi_right << std::endl;

            if (result.converged)
            {
                std::array<float, 24> q_solved{};
                for (std::size_t i = 0; i < Robot::dimension; ++i)
                {
                    q_solved[i] = result.q[i];
                }

                // q_solved's own base is fixed at the origin (see
                // torso_free_loss_jacobian's header comment), so its own "world" frame IS
                // q_start's base frame -- compare against t_base_mid (the goal already
                // expressed in that frame), not t_world_mid (q_start's TRUE world-frame
                // midpoint, which only coincides with t_base_mid when q_start's own base
                // happens to be at the origin too, as every example in this log's dataset is).
                const Eigen::Isometry3f solved_left_base = Robot::eefk(q_solved, 0);
                const Eigen::Isometry3f solved_right_base = Robot::eefk(q_solved, 1);
                Eigen::Isometry3f solved_mid_base = Eigen::Isometry3f::Identity();
                solved_mid_base.translation() =
                    0.5F * (solved_left_base.translation() + solved_right_base.translation());

                const float mid_translation_error =
                    (solved_mid_base.translation() - t_base_mid.translation()).norm();
                std::cout << "  [" << label << "] achieved mid-pose translation error vs. goal: "
                           << mid_translation_error << " m" << std::endl;
            }
        };

        report(
            "gradient_descent",
            ParameterizedSpace::solve_torso_for_mid_pose_gradient_descent(
                torso_init, t_mid_pose, psi_left_init, psi_right_init));
        report(
            "lm_inner",
            ParameterizedSpace::solve_torso_for_mid_pose_lm_inner(
                torso_init, t_mid_pose, psi_left_init, psi_right_init));

        // Step 5: block/FloatVector counterparts -- rake attempts at once (lane 0 == the same
        // {0,0,0,0,0,0}/0/0 starting point as step 4, the rest randomly sampled), stopping as
        // soon as any lane converges.
        const auto block_inits = sample_block_inits(rng);

        auto report_block = [&](const std::string &label, const auto &result)
        {
            std::cout << "  [" << label << "] converged = " << std::boolalpha << result.converged << ", lane = "
                       << result.lane << ", iterations = " << result.iterations << ", loss_left = "
                       << result.loss_left << ", loss_right = " << result.loss_right << std::endl;
            std::cout << "  [" << label << "] torso = (";
            for (std::size_t i = 0; i < 6; ++i)
            {
                std::cout << result.torso[i] << (i + 1 < 6 ? ", " : "");
            }
            std::cout << "), psi_left = " << result.psi_left << ", psi_right = " << result.psi_right << std::endl;

            if (result.converged)
            {
                std::array<float, 24> q_solved{};
                for (std::size_t i = 0; i < Robot::dimension; ++i)
                {
                    q_solved[i] = result.q[i];
                }

                // q_solved's own base is fixed at the origin (see
                // torso_free_loss_jacobian's header comment), so its own "world" frame IS
                // q_start's base frame -- compare against t_base_mid (the goal already
                // expressed in that frame), not t_world_mid (q_start's TRUE world-frame
                // midpoint, which only coincides with t_base_mid when q_start's own base
                // happens to be at the origin too, as every example in this log's dataset is).
                const Eigen::Isometry3f solved_left_base = Robot::eefk(q_solved, 0);
                const Eigen::Isometry3f solved_right_base = Robot::eefk(q_solved, 1);
                Eigen::Isometry3f solved_mid_base = Eigen::Isometry3f::Identity();
                solved_mid_base.translation() =
                    0.5F * (solved_left_base.translation() + solved_right_base.translation());

                const float mid_translation_error =
                    (solved_mid_base.translation() - t_base_mid.translation()).norm();
                std::cout << "  [" << label << "] achieved mid-pose translation error vs. goal: "
                           << mid_translation_error << " m" << std::endl;
            }
        };

        report_block(
            "block_gradient_descent",
            ParameterizedSpace::solve_torso_for_mid_pose_block_gradient_descent<rake>(
                block_inits.torso, t_mid_pose, block_inits.psi_left, block_inits.psi_right));
        report_block(
            "block_lm_inner",
            ParameterizedSpace::solve_torso_for_mid_pose_block_lm_inner<rake>(
                block_inits.torso, t_mid_pose, block_inits.psi_left, block_inits.psi_right));
    }
}  // namespace

auto main(int argc, char **argv) -> int
{
    const std::string default_path =
        "/src/rby1-constrained-planning/vamp_rrtc_logs/rrtc_calls.jsonl";
    const std::string path = (argc > 1) ? argv[1] : default_path;
    const std::size_t num_examples = (argc > 2) ? static_cast<std::size_t>(std::stoul(argv[2])) : 3;

    std::cout << "Loading up to " << num_examples << " example(s) from " << path << std::endl;
    const auto q_starts = load_q_starts(path, num_examples);
    std::cout << "Loaded " << q_starts.size() << " example(s)." << std::endl;

    std::mt19937 rng(std::random_device{}());
    for (std::size_t i = 0; i < q_starts.size(); ++i)
    {
        run_one_example(i, q_starts[i], rng);
    }

    return 0;
}
