"""Python port of scripts/cpp/compute_ik_test.cc: smoke test for
vamp.rby1.parameterized_space's torso/free-joint feasibility search
(torso_free_loss_jacobian / solve_torso_for_mid_pose_gradient_descent / _lm_inner, and their
block/FloatVector counterparts), generated by cricket's derive_rby1_parameterized_traces /
RainbowConstrainedBimanualIkCG's `compute_gradient` mode -- see cricket's
src/parameterization/rainbow_ik_cg.hh and resources/templates/fk_template.hh.

These differentiate the closed-form arm IK's feasibility loss back through the real
base->torso forward kinematics, and do gradient-based search over
[torso_0..5, psi_left, psi_right] (the wheeled base held fixed at the origin) to make a
goal mid-pose reachable.

For each of a handful of already-solved whole-body configurations logged by ruby's live
planner (rby1-constrained-planning/vamp_rrtc_logs/rrtc_calls.jsonl -- q_start/q_goal,
vamp.rby1.dimension() == 24 floats each), this:
  1. computes ee_left/ee_right world poses from q_start via vamp.rby1.eefk(q, eef_index),
  2. derives the goal mid-pose T_mid the same way ParameterizedSpace.compute_mid_pose does
     (translation midpoint of the two hands, identity rotation) in WORLD frame, then
     re-expresses it in q_start's own BASE frame (base_x, base_y, base_rz) -- since the
     solve always treats the base as fixed at the origin, this is the frame its T_mid input
     actually needs to be given in;
  3. reads off q_start's own (elbow_sel, shoulder_sel, wrist_sel) GCP branch per arm via
     param.classify_smm and locks the solve onto that same branch (the solve searches
     torso/psi on a FIXED branch, not across branches -- see RainbowConstrainedBimanualIkCG's
     header comment in rainbow_ik_cg.hh);
  4. starting from torso = [0, 0, 0, 0, 0, 0] (per this test's whole point -- can the torso
     be found from scratch, not just refined from the logged solution?) and an arbitrary
     psi_left/psi_right = 0 guess, runs both solve_torso_for_mid_pose_gradient_descent and
     solve_torso_for_mid_pose_lm_inner, reporting whether each converged, in how many
     iterations, and how far the resulting hands ended up from the goal mid-pose;
  5. does the same again with the block/FloatVector counterparts
     (solve_torso_for_mid_pose_block_gradient_descent/_lm_inner): param.rake attempts at
     once, lane 0 forced to the same [0,0,0,0,0,0]/0/0 starting point as step 4, the
     remaining lanes randomly sampled (torso within its own joint limits, psi in
     [0, 2*pi)) -- the sampling itself is this script's job, not the binding's (see
     fk_template.hh's solve_torso_for_mid_pose_block_impl header comment for why).

Usage:
    python scripts/compute_ik_test.py
    python scripts/compute_ik_test.py --path path/to/rrtc_calls.jsonl --num_examples 5
"""

import json
import math

import numpy as np
import vamp
from fire import Fire

DEFAULT_PATH = "/home/olorin/projects/PVAMP/rby1-constrained-planning/vamp_rrtc_logs/rrtc_calls.jsonl"


def load_q_starts(path: str, max_examples: int) -> list[np.ndarray]:
    """Up to `max_examples` "leg" (real reach-to-grasp problem, not a throwaway "probe"
    feasibility check) entries with a 24-float q_start from a .jsonl log, one JSON object
    per line."""
    q_starts = []
    with open(path) as f:
        for line in f:
            if len(q_starts) >= max_examples:
                break
            line = line.strip()
            if not line:
                continue

            entry = json.loads(line)
            if entry.get("kind") != "leg":
                continue
            if not entry.get("solved", True):
                continue
            if "q_start" not in entry:
                continue

            q_start = np.asarray(entry["q_start"], dtype=np.float32)
            if q_start.shape != (24,):
                continue

            q_starts.append(q_start)

    return q_starts


def base_frame_mid_pose(ambient, q_start: np.ndarray) -> np.ndarray:
    """Goal mid-pose derived from q_start's own hands (ee_left/ee_right), the same way
    ParameterizedSpace.compute_mid_pose does (translation midpoint, identity rotation) --
    then re-expressed in q_start's own base frame (base_x, base_y, base_rz), since the
    solve always treats the base as fixed at the origin.

    Since T_world_mid has an IDENTITY rotation by construction, T_base_mid = T_world_base^-1
    * T_world_mid works out to a plain rotation-by-(-base_rz) of the translation offset --
    no general 4x4 inverse needed.
    """
    ee_left_world = ambient.eefk(q_start, 0)
    ee_right_world = ambient.eefk(q_start, 1)
    t_world_mid = 0.5 * (ee_left_world[:3, 3] + ee_right_world[:3, 3])

    base_x, base_y = float(q_start[0]), float(q_start[1])
    base_rz = math.atan2(float(q_start[3]), float(q_start[2]))

    cos_rz, sin_rz = math.cos(-base_rz), math.sin(-base_rz)
    dx, dy = t_world_mid[0] - base_x, t_world_mid[1] - base_y
    t_base_mid_x = cos_rz * dx - sin_rz * dy
    t_base_mid_y = sin_rz * dx + cos_rz * dy
    t_base_mid_z = float(t_world_mid[2])

    half = -base_rz / 2.0
    t_mid_pose_base = np.array(
        [t_base_mid_x, t_base_mid_y, t_base_mid_z, 0.0, 0.0, math.sin(half), math.cos(half)],
        dtype=np.float32,
    )

    return t_mid_pose_base


def sample_block_inits(param, ambient, rng: np.random.Generator):
    """param.rake [torso, psi_left, psi_right] starting points for
    solve_torso_for_mid_pose_block_*: lane 0 forced to [0,0,0,0,0,0]/0/0 (the same starting
    point this script's scalar solve uses), lanes 1..rake-1 drawn uniformly at random --
    torso within ambient.lower_bounds()/upper_bounds()'s own torso_0..5 slice (ambient
    indices [4:10)), psi in [0, 2*pi)."""
    rake = param.rake
    lower = np.asarray(ambient.lower_bounds(), dtype=np.float32)[4:10]
    upper = np.asarray(ambient.upper_bounds(), dtype=np.float32)[4:10]

    torso_inits = np.zeros((rake, 6), dtype=np.float32)
    psi_left_inits = np.zeros(rake, dtype=np.float32)
    psi_right_inits = np.zeros(rake, dtype=np.float32)

    for lane in range(1, rake):
        torso_inits[lane] = rng.uniform(lower, upper).astype(np.float32)
        psi_left_inits[lane] = rng.uniform(0.0, 2.0 * math.pi)
        psi_right_inits[lane] = rng.uniform(0.0, 2.0 * math.pi)

    return torso_inits, psi_left_inits, psi_right_inits


def report(label: str, result) -> None:
    print(
        f"  [{label}] converged = {result.converged}, iterations = {result.iterations}, "
        f"loss_left = {result.loss_left:.6g}, loss_right = {result.loss_right:.6g}"
    )
    print(f"  [{label}] torso = {list(result.torso)}, psi_left = {result.psi_left:.4f}, "
          f"psi_right = {result.psi_right:.4f}")


def report_block(label: str, result) -> None:
    print(
        f"  [{label}] converged = {result.converged}, lane = {result.lane}, "
        f"iterations = {result.iterations}, loss_left = {result.loss_left:.6g}, "
        f"loss_right = {result.loss_right:.6g}"
    )
    print(f"  [{label}] torso = {list(result.torso)}, psi_left = {result.psi_left:.4f}, "
          f"psi_right = {result.psi_right:.4f}")


def achieved_mid_translation_error(ambient, q_solved: np.ndarray, t_mid_pose_base: np.ndarray) -> float:
    """q_solved's own base is fixed at the origin (see torso_free_loss_jacobian's header
    comment), so its own "world" frame IS q_start's base frame -- compare its achieved
    mid-pose translation directly against t_mid_pose_base (the goal already expressed in
    that frame)."""
    q_solved = np.asarray(q_solved, dtype=np.float32)
    solved_left = ambient.eefk(q_solved, 0)
    solved_right = ambient.eefk(q_solved, 1)
    solved_mid = 0.5 * (solved_left[:3, 3] + solved_right[:3, 3])
    return float(np.linalg.norm(solved_mid - t_mid_pose_base[:3]))


def run_one_example(index: int, q_start: np.ndarray, ambient, param, rng: np.random.Generator) -> None:
    print(f"\n=== example {index} ===")

    # Steps 1-2: goal mid-pose, base frame.
    t_mid_pose = base_frame_mid_pose(ambient, q_start)
    base_rz = math.atan2(float(q_start[3]), float(q_start[2]))
    print(f"  base pose (x, y, rz): ({q_start[0]:.4f}, {q_start[1]:.4f}, {base_rz:.4f})")
    print(f"  goal mid-pose (base frame): ({t_mid_pose[0]:.4f}, {t_mid_pose[1]:.4f}, {t_mid_pose[2]:.4f})")

    # Step 3: lock the solve onto q_start's own GCP branch.
    left_gcp, right_gcp = param.classify_smm(q_start)
    param.set_gcp(left_gcp, right_gcp)
    print(f"  left_gcp: {list(left_gcp)}, right_gcp: {list(right_gcp)}")

    # Step 4: solve from torso = 0, psi = 0 -- both solvers, reported side by side.
    torso_init = np.zeros(6, dtype=np.float32)
    psi_left_init = 0.0
    psi_right_init = 0.0

    gd_result = param.solve_torso_for_mid_pose_gradient_descent(
        torso_init, t_mid_pose, psi_left_init, psi_right_init)
    report("gradient_descent", gd_result)
    if gd_result.converged:
        error = achieved_mid_translation_error(ambient, gd_result.q, t_mid_pose)
        print(f"  [gradient_descent] achieved mid-pose translation error vs. goal: {error:.6g} m")

    lm_result = param.solve_torso_for_mid_pose_lm_inner(
        torso_init, t_mid_pose, psi_left_init, psi_right_init)
    report("lm_inner", lm_result)
    if lm_result.converged:
        error = achieved_mid_translation_error(ambient, lm_result.q, t_mid_pose)
        print(f"  [lm_inner] achieved mid-pose translation error vs. goal: {error:.6g} m")

    # Step 5: block/FloatVector counterparts -- param.rake attempts at once (lane 0 == the
    # same [0,0,0,0,0,0]/0/0 starting point as step 4, the rest randomly sampled), stopping
    # as soon as any lane converges.
    torso_inits, psi_left_inits, psi_right_inits = sample_block_inits(param, ambient, rng)

    block_gd_result = param.solve_torso_for_mid_pose_block_gradient_descent(
        torso_inits, t_mid_pose, psi_left_inits, psi_right_inits)
    report_block("block_gradient_descent", block_gd_result)
    if block_gd_result.converged:
        error = achieved_mid_translation_error(ambient, block_gd_result.q, t_mid_pose)
        print(f"  [block_gradient_descent] achieved mid-pose translation error vs. goal: {error:.6g} m")

    block_lm_result = param.solve_torso_for_mid_pose_block_lm_inner(
        torso_inits, t_mid_pose, psi_left_inits, psi_right_inits)
    report_block("block_lm_inner", block_lm_result)
    if block_lm_result.converged:
        error = achieved_mid_translation_error(ambient, block_lm_result.q, t_mid_pose)
        print(f"  [block_lm_inner] achieved mid-pose translation error vs. goal: {error:.6g} m")


def main(path: str = DEFAULT_PATH, num_examples: int = 3, seed: int | None = None):
    ambient = vamp.rby1
    param = ambient.parameterized_space

    print(f"Loading up to {num_examples} example(s) from {path}")
    q_starts = load_q_starts(path, num_examples)
    print(f"Loaded {len(q_starts)} example(s).")
    print(f"param.rake (SIMD block width): {param.rake}")

    rng = np.random.default_rng(seed)
    for index, q_start in enumerate(q_starts):
        run_one_example(index, q_start, ambient, param, rng)


if __name__ == "__main__":
    Fire(main)
