"""Python port of scripts/cpp/compute_ik_test.cc: smoke test for
vamp.rby1.parameterized_space's torso/free-joint feasibility search
(torso_free_loss_jacobian / solve_torso_for_mid_pose_gradient_descent / _lm_inner, and their
block/FloatVector counterparts), generated by cricket's derive_rby1_parameterized_traces /
RainbowConstrainedBimanualIkCG's `compute_gradient` mode -- see cricket's
src/parameterization/rainbow_ik_cg.hh and resources/templates/fk_template.hh.

These differentiate the closed-form arm IK's feasibility loss back through the real
base->torso forward kinematics, and do gradient-based search over
[torso_0..5, psi_left, psi_right] (the wheeled base held fixed at the origin) to make a
goal mid-pose reachable.

For each of a handful of already-solved whole-body configurations logged by ruby's live
planner (rby1-constrained-planning/vamp_rrtc_logs/rrtc_calls.jsonl -- q_start/q_goal,
vamp.rby1.dimension() == 24 floats each), this:
  1. computes ee_left/ee_right world poses from q_start via vamp.rby1.eefk(q, eef_index),
  2. derives the goal mid-pose T_mid the same way ParameterizedSpace.compute_mid_pose does
     (translation midpoint of the two hands, identity rotation) in WORLD frame, then
     re-expresses it in q_start's own BASE frame (base_x, base_y, base_rz) -- since the
     solve always treats the base as fixed at the origin, this is the frame its T_mid input
     actually needs to be given in;
  3. reads off q_start's own (elbow_sel, shoulder_sel, wrist_sel) GCP branch per arm via
     param.classify_smm and locks the solve onto that same branch (the solve searches
     torso/psi on a FIXED branch, not across branches -- see RainbowConstrainedBimanualIkCG's
     header comment in rainbow_ik_cg.hh);
  4. starting from torso = [0, 0, 0, 0, 0, 0] (per this test's whole point -- can the torso
     be found from scratch, not just refined from the logged solution?) and an arbitrary
     psi_left/psi_right = 0 guess, runs both solve_torso_for_mid_pose_gradient_descent and
     solve_torso_for_mid_pose_lm_inner, reporting whether each converged, in how many
     iterations, and how far the resulting hands ended up from the goal mid-pose;
  5. does the same again with the block/FloatVector counterparts
     (solve_torso_for_mid_pose_block_gradient_descent/_lm_inner): param.rake attempts at
     once, lane 0 forced to the same [0,0,0,0,0,0]/0/0 starting point as step 4, the
     remaining lanes randomly sampled (torso within its own joint limits, psi in
     [0, 2*pi)) -- the sampling itself is this script's job, not the binding's (see
     fk_template.hh's solve_torso_for_mid_pose_block_impl header comment for why).
  6. repeats steps 4-5 against the INDEPENDENT (unconstrained) counterpart
     (solve_torso_for_independent_poses_gradient_descent/_lm_inner + block variants),
     generated by cricket's RainbowIkCG `compute_gradient` mode. There's no ground-truth
     data with genuinely independent left/right targets to hand this, so this script's
     stand-in is to split q_start's own already-solved mid-pose apart: each hand's OWN full
     pose (translation + orientation, not just the mid-pose's translation-only/identity-
     rotation target) expressed in q_start's base frame -- see base_frame_left_right_poses.
     Every other step is identical to 4-5: same q_start, same GCP branch, same torso = 0
     cold start.

Usage:
    python scripts/compute_ik_test.py
    python scripts/compute_ik_test.py --path path/to/rrtc_calls.jsonl --num_examples 5

    # Also launch a viser viz with TWO independent sliders (URDF path hardcoded via
    # RBY1_URDF_DIR/RBY1_URDF_NAME below), each with its own robot instance so both solves
    # can be inspected side by side:
    #   "Mid-pose example" -- places a frame at the desired eef mid-pose and poses the first
    #   robot at the solve_torso_for_mid_pose_lm_inner solution for it.
    #   "Independent example" -- places two frames (left/right goal poses) and poses the
    #   second robot (offset sideways) at the solve_torso_for_independent_poses_lm_inner
    #   solution reaching for both simultaneously.
    python scripts/compute_ik_test.py --viz
"""

import json
import math
import time
from pathlib import Path

import numpy as np
import vamp
from fire import Fire
from scipy.spatial.transform import Rotation

DEFAULT_PATH = "/home/olorin/projects/PVAMP/rby1-constrained-planning/vamp_rrtc_logs/rrtc_calls.jsonl"

# TODO: hardcode these to point at the rby1 URDF you want rendered in --viz mode.
RBY1_URDF_DIR = Path("/src/cricket/resources/ruby/rby1_description_drake/xacro/")
RBY1_URDF_NAME = "rby1_with_holonomic_base_spherized.urdf"


def load_q_starts(path: str, max_examples: int) -> list[np.ndarray]:
    """Up to `max_examples` "leg" (real reach-to-grasp problem, not a throwaway "probe"
    feasibility check) entries with a 24-float q_start from a .jsonl log, one JSON object
    per line."""
    q_starts = []
    with open(path) as f:
        for line in f:
            if len(q_starts) >= max_examples:
                break
            line = line.strip()
            if not line:
                continue

            entry = json.loads(line)
            if entry.get("kind") != "leg":
                continue
            if not entry.get("solved", True):
                continue
            if "q_start" not in entry:
                continue

            q_start = np.asarray(entry["q_start"], dtype=np.float32)
            if q_start.shape != (24,):
                continue

            q_starts.append(q_start)

    return q_starts


def base_frame_mid_pose(ambient, q_start: np.ndarray) -> np.ndarray:
    """Goal mid-pose derived from q_start's own hands (ee_left/ee_right), the same way
    ParameterizedSpace.compute_mid_pose does (translation midpoint, identity rotation) --
    then re-expressed in q_start's own base frame (base_x, base_y, base_rz), since the
    solve always treats the base as fixed at the origin.

    Since T_world_mid has an IDENTITY rotation by construction, T_base_mid = T_world_base^-1
    * T_world_mid works out to a plain rotation-by-(-base_rz) of the translation offset --
    no general 4x4 inverse needed.
    """
    ee_left_world = ambient.eefk(q_start, 0)
    ee_right_world = ambient.eefk(q_start, 1)
    t_world_mid = 0.5 * (ee_left_world[:3, 3] + ee_right_world[:3, 3])

    base_x, base_y = float(q_start[0]), float(q_start[1])
    base_rz = math.atan2(float(q_start[3]), float(q_start[2]))

    cos_rz, sin_rz = math.cos(-base_rz), math.sin(-base_rz)
    dx, dy = t_world_mid[0] - base_x, t_world_mid[1] - base_y
    t_base_mid_x = cos_rz * dx - sin_rz * dy
    t_base_mid_y = sin_rz * dx + cos_rz * dy
    t_base_mid_z = float(t_world_mid[2])

    half = -base_rz / 2.0
    t_mid_pose_base = np.array(
        [t_base_mid_x, t_base_mid_y, t_base_mid_z, 0.0, 0.0, math.sin(half), math.cos(half)],
        dtype=np.float32,
    )

    return t_mid_pose_base


def base_frame_left_right_poses(ambient, q_start: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Independent-pose counterpart of base_frame_mid_pose, for
    solve_torso_for_independent_poses_* (no shared mid-frame -- each hand's FULL pose,
    translation + orientation, expressed in q_start's own base frame). There's no
    ground-truth data with genuinely independent left/right targets to test this against, so
    this is this script's stand-in: split q_start's own already-solved hands apart instead of
    collapsing them into one translation-only, identity-rotation mid-pose target. Unlike
    base_frame_mid_pose, the rotation isn't identity here, so this needs the actual
    T_base_world^-1 @ T_world_hand composition (translation-only shortcut doesn't apply)."""
    base_x, base_y = float(q_start[0]), float(q_start[1])
    base_rz = math.atan2(float(q_start[3]), float(q_start[2]))
    cos_rz, sin_rz = math.cos(-base_rz), math.sin(-base_rz)
    r_base_world = np.array(
        [[cos_rz, -sin_rz, 0.0], [sin_rz, cos_rz, 0.0], [0.0, 0.0, 1.0]], dtype=np.float64)

    def to_base_pose(ee_world: np.ndarray) -> np.ndarray:
        t_world = ee_world[:3, 3].astype(np.float64)
        r_world = ee_world[:3, :3].astype(np.float64)
        d = t_world - np.array([base_x, base_y, 0.0])
        t_base = r_base_world @ d
        r_base = r_base_world @ r_world
        qx, qy, qz, qw = Rotation.from_matrix(r_base).as_quat()
        return np.array([t_base[0], t_base[1], t_base[2], qx, qy, qz, qw], dtype=np.float32)

    ee_left_world = ambient.eefk(q_start, 0)
    ee_right_world = ambient.eefk(q_start, 1)
    return to_base_pose(ee_left_world), to_base_pose(ee_right_world)


def sample_block_inits(param, ambient, rng: np.random.Generator):
    """param.rake [torso, psi_left, psi_right] starting points for
    solve_torso_for_mid_pose_block_*: lane 0 forced to [0,0,0,0,0,0]/0/0 (the same starting
    point this script's scalar solve uses), lanes 1..rake-1 drawn uniformly at random --
    torso within ambient.lower_bounds()/upper_bounds()'s own torso_0..5 slice (ambient
    indices [4:10)), psi in [0, 2*pi)."""
    rake = param.rake
    lower = np.asarray(ambient.lower_bounds(), dtype=np.float32)[4:10]
    upper = np.asarray(ambient.upper_bounds(), dtype=np.float32)[4:10]

    torso_inits = np.zeros((rake, 6), dtype=np.float32)
    psi_left_inits = np.zeros(rake, dtype=np.float32)
    psi_right_inits = np.zeros(rake, dtype=np.float32)

    for lane in range(1, rake):
        torso_inits[lane] = rng.uniform(lower, upper).astype(np.float32)
        psi_left_inits[lane] = rng.uniform(0.0, 2.0 * math.pi)
        psi_right_inits[lane] = rng.uniform(0.0, 2.0 * math.pi)

    # Reused as-is for solve_torso_for_independent_poses_block_* below -- same shape
    # ([torso, free_joint_left, free_joint_right] per lane), just a different pair of names
    # (left_j15/right_j24) for what's still the same free-joint angle at the call site.
    return torso_inits, psi_left_inits, psi_right_inits


def report(label: str, result) -> None:
    print(
        f"  [{label}] converged = {result.converged}, iterations = {result.iterations}, "
        f"loss_left = {result.loss_left:.6g}, loss_right = {result.loss_right:.6g}"
    )
    print(f"  [{label}] torso = {list(result.torso)}, psi_left = {result.psi_left:.4f}, "
          f"psi_right = {result.psi_right:.4f}")


def report_block(label: str, result) -> None:
    print(
        f"  [{label}] converged = {result.converged}, lane = {result.lane}, "
        f"iterations = {result.iterations}, loss_left = {result.loss_left:.6g}, "
        f"loss_right = {result.loss_right:.6g}"
    )
    print(f"  [{label}] torso = {list(result.torso)}, psi_left = {result.psi_left:.4f}, "
          f"psi_right = {result.psi_right:.4f}")


def report_independent(label: str, result) -> None:
    print(
        f"  [{label}] converged = {result.converged}, iterations = {result.iterations}, "
        f"loss_left = {result.loss_left:.6g}, loss_right = {result.loss_right:.6g}"
    )
    print(f"  [{label}] torso = {list(result.torso)}, left_j15 = {result.left_j15:.4f}, "
          f"right_j24 = {result.right_j24:.4f}")


def report_independent_block(label: str, result) -> None:
    print(
        f"  [{label}] converged = {result.converged}, lane = {result.lane}, "
        f"iterations = {result.iterations}, loss_left = {result.loss_left:.6g}, "
        f"loss_right = {result.loss_right:.6g}"
    )
    print(f"  [{label}] torso = {list(result.torso)}, left_j15 = {result.left_j15:.4f}, "
          f"right_j24 = {result.right_j24:.4f}")


def achieved_mid_translation_error(ambient, q_solved: np.ndarray, t_mid_pose_base: np.ndarray) -> float:
    """q_solved's own base is fixed at the origin (see torso_free_loss_jacobian's header
    comment), so its own "world" frame IS q_start's base frame -- compare its achieved
    mid-pose translation directly against t_mid_pose_base (the goal already expressed in
    that frame)."""
    q_solved = np.asarray(q_solved, dtype=np.float32)
    solved_left = ambient.eefk(q_solved, 0)
    solved_right = ambient.eefk(q_solved, 1)
    solved_mid = 0.5 * (solved_left[:3, 3] + solved_right[:3, 3])
    return float(np.linalg.norm(solved_mid - t_mid_pose_base[:3]))


def achieved_independent_pose_error(
    ambient, q_solved: np.ndarray, left_pose_base: np.ndarray, right_pose_base: np.ndarray
) -> tuple[float, float]:
    """Per-hand translation error, same base-frame convention as
    achieved_mid_translation_error above (q_solved's own base is fixed at the origin, so its
    own "world" frame IS the frame left_pose_base/right_pose_base are already given in)."""
    q_solved = np.asarray(q_solved, dtype=np.float32)
    solved_left = ambient.eefk(q_solved, 0)
    solved_right = ambient.eefk(q_solved, 1)
    left_error = float(np.linalg.norm(solved_left[:3, 3] - left_pose_base[:3]))
    right_error = float(np.linalg.norm(solved_right[:3, 3] - right_pose_base[:3]))
    return left_error, right_error


def run_one_example(index: int, q_start: np.ndarray, ambient, param, rng: np.random.Generator) -> None:
    print(f"\n=== example {index} ===")

    # Sets the thread-local t_mid_left/t_mid_right hand offsets from q_start's own hands,
    # so the solve targets each hand's actual offset from the mid-pose instead of the
    # identity default (both hands coinciding with T_mid).
    param.compute_mid_pose(q_start)

    # Steps 1-2: goal mid-pose, base frame.
    t_mid_pose = base_frame_mid_pose(ambient, q_start)
    base_rz = math.atan2(float(q_start[3]), float(q_start[2]))
    print(f"  base pose (x, y, rz): ({q_start[0]:.4f}, {q_start[1]:.4f}, {base_rz:.4f})")
    print(f"  goal mid-pose (base frame): ({t_mid_pose[0]:.4f}, {t_mid_pose[1]:.4f}, {t_mid_pose[2]:.4f})")

    # Step 3: lock the solve onto q_start's own GCP branch.
    left_gcp, right_gcp = param.classify_smm(q_start)
    param.set_gcp(left_gcp, right_gcp)
    print(f"  left_gcp: {list(left_gcp)}, right_gcp: {list(right_gcp)}")

    # Step 4: solve from torso = 0, psi = 0 -- both solvers, reported side by side.
    torso_init = np.zeros(6, dtype=np.float32)
    psi_left_init = 0.0
    psi_right_init = 0.0

    gd_result = param.solve_torso_for_mid_pose_gradient_descent(
        torso_init, t_mid_pose, psi_left_init, psi_right_init)
    report("gradient_descent", gd_result)
    if gd_result.converged:
        error = achieved_mid_translation_error(ambient, gd_result.q, t_mid_pose)
        print(f"  [gradient_descent] achieved mid-pose translation error vs. goal: {error:.6g} m")

    lm_result = param.solve_torso_for_mid_pose_lm_inner(
        torso_init, t_mid_pose, psi_left_init, psi_right_init)
    report("lm_inner", lm_result)
    if lm_result.converged:
        error = achieved_mid_translation_error(ambient, lm_result.q, t_mid_pose)
        print(f"  [lm_inner] achieved mid-pose translation error vs. goal: {error:.6g} m")

    # Step 5: block/FloatVector counterparts -- param.rake attempts at once (lane 0 == the
    # same [0,0,0,0,0,0]/0/0 starting point as step 4, the rest randomly sampled), stopping
    # as soon as any lane converges.
    torso_inits, psi_left_inits, psi_right_inits = sample_block_inits(param, ambient, rng)

    block_gd_result = param.solve_torso_for_mid_pose_block_gradient_descent(
        torso_inits, t_mid_pose, psi_left_inits, psi_right_inits)
    report_block("block_gradient_descent", block_gd_result)
    if block_gd_result.converged:
        error = achieved_mid_translation_error(ambient, block_gd_result.q, t_mid_pose)
        print(f"  [block_gradient_descent] achieved mid-pose translation error vs. goal: {error:.6g} m")

    block_lm_result = param.solve_torso_for_mid_pose_block_lm_inner(
        torso_inits, t_mid_pose, psi_left_inits, psi_right_inits)
    report_block("block_lm_inner", block_lm_result)
    if block_lm_result.converged:
        error = achieved_mid_translation_error(ambient, block_lm_result.q, t_mid_pose)
        print(f"  [block_lm_inner] achieved mid-pose translation error vs. goal: {error:.6g} m")

    # Step 6: independent (unconstrained) counterpart. No ground-truth independent
    # left/right target data exists, so this is fed q_start's own mid-pose split back apart
    # into each hand's own full pose (see base_frame_left_right_poses) instead -- same
    # q_start, same GCP branch, same torso = 0 cold start as steps 4-5 above.
    left_pose, right_pose = base_frame_left_right_poses(ambient, q_start)
    print(f"  goal left pose (base frame): ({left_pose[0]:.4f}, {left_pose[1]:.4f}, {left_pose[2]:.4f})")
    print(f"  goal right pose (base frame): ({right_pose[0]:.4f}, {right_pose[1]:.4f}, {right_pose[2]:.4f})")

    left_j15_init = 0.0
    right_j24_init = 0.0

    ind_gd_result = param.solve_torso_for_independent_poses_gradient_descent(
        torso_init, left_pose, right_pose, left_j15_init, right_j24_init)
    report_independent("independent_gradient_descent", ind_gd_result)
    if ind_gd_result.converged:
        left_err, right_err = achieved_independent_pose_error(ambient, ind_gd_result.q, left_pose, right_pose)
        print(f"  [independent_gradient_descent] achieved translation error vs. goal: "
              f"left={left_err:.6g} m, right={right_err:.6g} m")

    ind_lm_result = param.solve_torso_for_independent_poses_lm_inner(
        torso_init, left_pose, right_pose, left_j15_init, right_j24_init)
    report_independent("independent_lm_inner", ind_lm_result)
    if ind_lm_result.converged:
        left_err, right_err = achieved_independent_pose_error(ambient, ind_lm_result.q, left_pose, right_pose)
        print(f"  [independent_lm_inner] achieved translation error vs. goal: "
              f"left={left_err:.6g} m, right={right_err:.6g} m")

    ind_torso_inits, ind_left_j15_inits, ind_right_j24_inits = sample_block_inits(param, ambient, rng)

    ind_block_gd_result = param.solve_torso_for_independent_poses_block_gradient_descent(
        ind_torso_inits, left_pose, right_pose, ind_left_j15_inits, ind_right_j24_inits)
    report_independent_block("independent_block_gradient_descent", ind_block_gd_result)
    if ind_block_gd_result.converged:
        left_err, right_err = achieved_independent_pose_error(
            ambient, ind_block_gd_result.q, left_pose, right_pose)
        print(f"  [independent_block_gradient_descent] achieved translation error vs. goal: "
              f"left={left_err:.6g} m, right={right_err:.6g} m")

    ind_block_lm_result = param.solve_torso_for_independent_poses_block_lm_inner(
        ind_torso_inits, left_pose, right_pose, ind_left_j15_inits, ind_right_j24_inits)
    report_independent_block("independent_block_lm_inner", ind_block_lm_result)
    if ind_block_lm_result.converged:
        left_err, right_err = achieved_independent_pose_error(
            ambient, ind_block_lm_result.q, left_pose, right_pose)
        print(f"  [independent_block_lm_inner] achieved translation error vs. goal: "
              f"left={left_err:.6g} m, right={right_err:.6g} m")


def build_viz_examples(q_starts: list, ambient, param) -> list:
    """For each q_start: the goal mid-pose (base frame) plus the goal left/right poses (base
    frame, see base_frame_left_right_poses), and both the solve_torso_for_mid_pose_lm_inner
    and solve_torso_for_independent_poses_lm_inner results reaching for them from
    torso = 0 -- everything run_viz's two sliders need to show per example."""
    examples = []
    for q_start in q_starts:
        param.compute_mid_pose(q_start)
        t_mid_pose = base_frame_mid_pose(ambient, q_start)
        left_pose, right_pose = base_frame_left_right_poses(ambient, q_start)

        left_gcp, right_gcp = param.classify_smm(q_start)
        param.set_gcp(left_gcp, right_gcp)

        lm_result = param.solve_torso_for_mid_pose_lm_inner(
            np.zeros(6, dtype=np.float32), t_mid_pose, 0.0, 0.0)
        ind_lm_result = param.solve_torso_for_independent_poses_lm_inner(
            np.zeros(6, dtype=np.float32), left_pose, right_pose, 0.0, 0.0)

        examples.append({
            "q_start": q_start,
            "t_mid_pose": t_mid_pose,
            "lm_result": lm_result,
            "left_pose": left_pose,
            "right_pose": right_pose,
            "ind_lm_result": ind_lm_result,
        })

    return examples


def to_viser_joint_config(q: np.ndarray) -> np.ndarray:
    """vamp.rby1's q encodes base yaw as (cos, sin) at indices [2, 3] (see
    base_frame_mid_pose's own atan2(q[3], q[2])); the URDF's holonomic base joint wants a
    single angle, so collapse those two into atan2(sin, cos) before handing the config to
    ViserUrdf.update_cfg."""
    q = np.asarray(q, dtype=np.float32)
    base_theta = math.atan2(float(q[3]), float(q[2]))
    return np.concatenate([q[:2], [base_theta], q[4:]]).astype(np.float32)


def _set_frame_from_pose(frame, pose: np.ndarray) -> None:
    """pose is (x, y, z, qx, qy, qz, qw); viser wants position + wxyz."""
    qx, qy, qz, qw = (float(v) for v in pose[3:7])
    frame.position = (float(pose[0]), float(pose[1]), float(pose[2]))
    frame.wxyz = (qw, qx, qy, qz)


def run_viz(examples: list) -> None:
    """Viser viz: TWO independent sliders, one per IK mode, each with its own robot instance
    (mode-2's URDF is loaded again and its root frame offset sideways so both are visible at
    once without one overwriting the other's pose):
      - "Mid-pose example" places a frame at that example's desired eef mid-pose (base frame)
        and poses mode-1's robot at the solve_torso_for_mid_pose_lm_inner solution reaching
        for it.
      - "Independent example" places two frames (left/right goal poses, base frame) and poses
        mode-2's robot at the solve_torso_for_independent_poses_lm_inner solution reaching
        for BOTH simultaneously.
    Both solves fix the base at the origin, so each robot's own root IS the base frame its
    own target frame(s) are drawn in -- for mode-2 that's relative to its offset root, which
    is exactly why the target frames are parented under it below rather than added at the
    top level.
    """
    import yourdfpy
    from viser.extras import ViserUrdf
    from viser_utils import setup_viser_with_robot

    server, robot = setup_viser_with_robot(RBY1_URDF_DIR, RBY1_URDF_NAME)
    target_frame = server.scene.add_frame(
        "/target_eef_mid_pose", axes_length=0.15, axes_radius=0.005)
    status_text = server.gui.add_text("Mid-pose IK status", initial_value="")

    # Second robot instance for the independent-pose mode, offset sideways so both solves can
    # be inspected side by side. The offset lives on the parent frame; the URDF and its target
    # frames are parented under it, so their own local coordinates stay exactly the base-frame
    # values the solve already returns/expects -- no re-deriving an offset pose by hand.
    server.scene.add_frame("/robot_independent", position=(0.0, 1.5, 0.0), show_axes=False)
    urdf = yourdfpy.URDF.load(str(RBY1_URDF_DIR / RBY1_URDF_NAME))
    robot_independent = ViserUrdf(
        server, urdf, load_meshes=True, load_collision_meshes=False,
        root_node_name="/robot_independent")
    target_left_frame = server.scene.add_frame(
        "/robot_independent/target_eef_left_pose", axes_length=0.15, axes_radius=0.005)
    target_right_frame = server.scene.add_frame(
        "/robot_independent/target_eef_right_pose", axes_length=0.15, axes_radius=0.005)
    status_text_independent = server.gui.add_text("Independent-pose IK status", initial_value="")

    def show_mid(index: int) -> None:
        example = examples[index]
        t_mid_pose = example["t_mid_pose"]
        lm_result = example["lm_result"]

        _set_frame_from_pose(target_frame, t_mid_pose)
        robot.update_cfg(to_viser_joint_config(lm_result.q))

        status_text.value = (
            f"example {index}: converged={lm_result.converged}, "
            f"iterations={lm_result.iterations}, loss_left={lm_result.loss_left:.4g}, "
            f"loss_right={lm_result.loss_right:.4g}"
        )

    def show_independent(index: int) -> None:
        example = examples[index]
        left_pose = example["left_pose"]
        right_pose = example["right_pose"]
        ind_lm_result = example["ind_lm_result"]

        _set_frame_from_pose(target_left_frame, left_pose)
        _set_frame_from_pose(target_right_frame, right_pose)
        robot_independent.update_cfg(to_viser_joint_config(ind_lm_result.q))

        status_text_independent.value = (
            f"example {index}: converged={ind_lm_result.converged}, "
            f"iterations={ind_lm_result.iterations}, loss_left={ind_lm_result.loss_left:.4g}, "
            f"loss_right={ind_lm_result.loss_right:.4g}"
        )

    show_mid(0)
    show_independent(0)

    example_slider = server.gui.add_slider(
        "Mid-pose example", min=0, max=len(examples) - 1, step=1, initial_value=0)

    @example_slider.on_update
    def _(event):
        show_mid(int(event.target.value))

    independent_slider = server.gui.add_slider(
        "Independent example", min=0, max=len(examples) - 1, step=1, initial_value=0)

    @independent_slider.on_update
    def _(event):
        show_independent(int(event.target.value))

    print("visualization at http://localhost:8080; ctrl-c to exit")
    while True:
        time.sleep(1.0)


def main(path: str = DEFAULT_PATH, num_examples: int = 3, seed: int | None = None,
         viz: bool = False):
    ambient = vamp.rby1
    param = ambient.parameterized_space

    print(f"Loading up to {num_examples} example(s) from {path}")
    q_starts = load_q_starts(path, num_examples)
    print(f"Loaded {len(q_starts)} example(s).")
    print(f"param.rake (SIMD block width): {param.rake}")

    rng = np.random.default_rng(seed)
    for index, q_start in enumerate(q_starts):
        run_one_example(index, q_start, ambient, param, rng)

    if viz:
        if not q_starts:
            raise ValueError("--viz requires at least one loaded example")
        examples = build_viz_examples(q_starts, ambient, param)
        run_viz(examples)


if __name__ == "__main__":
    Fire(main)
